FROM python:3.11

# LibreOffice install
RUN apt-get update && apt-get install -y libreoffice

# Working folder
WORKDIR /app

# Saare files copy
COPY . .

# Python dependencies install
RUN pip install -r requirements.txt

# Server run
CMD ["gunicorn", "server:app", "--bind", "0.0.0.0:10000"]