services:
  - type: web
    name: hope-energy
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y libreoffice
      pip install -r requirements.txt
    startCommand: gunicorn server:app